### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by noobLei** [python/psf-infra-meta#137]
Traceback (most recent call last):
  File "python_AFL.py", line 110, in runFuzzer
    runtime = runApplication(input_path, mode)
  File "python_AFL.py", line 75, in runApplication
    exec(f.read(), {'buff': input_data})   
  File "<string>", line 16, in <module>
  File "<string>", line 10, in fuzz
  File "/usr/lib/python3.6/codeop.py", line 122, in compile_command
    return _maybe_compile(_compile, source, filename, symbol)
  File "/usr/lib/python3.6/codeop.py", line 82, in _maybe_compile
    code = compiler(source, filename, symbol)
  File "/usr/lib/python3.6/codeop.py", line 102, in _compile
    return compile(source, filename, symbol, PyCF_DONT_IMPLY_DEDENT)
MemoryError

when I use  codeop.compile_command( random input ),  I get the error .
I wonder if I found the error with the Python codeop's library？？

**Comment by matrixise** [comment]
This issue is related to Python. Please use the user mailing https://www.python.org/community/lists/
