### ISSUE TITLE
Python 3.9.0 Gives Me Keyword Problems

### ISSUE THREAD

**Issue by allen546** [python/psf-infra-meta#84]
When I tried imapclient, It gives me a full traceback down to imaplib. Here it is:
Traceback (most recent call last):
  File "C:/Users/lshom/AppData/Local/Programs/Python/Python39/email_explore.py", line 147, in <module>
    main()
  File "C:/Users/lshom/AppData/Local/Programs/Python/Python39/email_explore.py", line 12, in main
    c = IMAPClient(hostname, ssl=True)
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python39\lib\site-packages\imapclient\imapclient.py", line 254, in __init__
    self._imap = self._create_IMAP4()
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python39\lib\site-packages\imapclient\imapclient.py", line 288, in _create_IMAP4
    return tls.IMAP4_TLS(self.host, self.port, self.ssl_context,
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python39\lib\site-packages\imapclient\tls.py", line 44, in __init__
    imaplib.IMAP4.__init__(self, host, port)
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python39\lib\imaplib.py", line 202, in __init__
    self.open(host=host, port=port, timeout=timeout)
TypeError: open() got an unexpected keyword argument 'timeout'

I think it's the python 3.9 interpreter's problem because I used it before on python 3.8 and it worked.

**Comment by pradyunsg** [comment]
Hi! Thanks for filing this but this isn't the right place for this issue.

I think that [python-tutor](https://mail.python.org/mailman/listinfo/tutor) mailing lists, [#python on Freenode](https://webchat.freenode.net/?channels=%23python) (IRC) or [StackOverflow](https://stackoverflow.com) would be better channels to get support for the issue you're facing.

**Comment by matrixise** [comment]
@pablogsal I don't have the access to this tracker, but this issue is unrelated to the PSF infra. Do you think you could close this one? Thanks

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
