### ISSUE TITLE
pip upgrade to 20.3.X on Windows 10

### ISSUE THREAD

**Issue by ceo-software-forge-de** [python/psf-infra-meta#92]
System: Windows 10 Home 64-bit, AMD Ryzon 5 3400G with Radeon Vega GPU
Python 3.9.0/3.9.1

C/C++ 14.16 (a. o.) VC 2019 Community Edition

Issue: Pip wants to use a certain "t64.exe" tool, which isn't installed - ...and "What for", i've to ask - does it have any purpose?
Issue output follows!

PS C:\Windows\system32> python -m pip install --upgrade pip
Collecting pip
  Using cached pip-20.3.1-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4
  Rolling back uninstall of pip
  Moving to c:\users\djiqu\appdata\roaming\python\python39\scripts\pip.exe
   from C:\Users\djiqu\AppData\Local\Temp\pip-uninstall-iy385bp0\pip.exe
  Moving to c:\users\djiqu\appdata\roaming\python\python39\scripts\pip3.9.exe
   from C:\Users\djiqu\AppData\Local\Temp\pip-uninstall-iy385bp0\pip3.9.exe
  Moving to c:\users\djiqu\appdata\roaming\python\python39\scripts\pip3.exe
   from C:\Users\djiqu\AppData\Local\Temp\pip-uninstall-iy385bp0\pip3.exe
  Moving to c:\users\djiqu\appdata\roaming\python\python39\site-packages\pip-20.2.4.dist-info\
   from C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\~ip-20.2.4.dist-info
  Moving to c:\users\djiqu\appdata\roaming\python\python39\site-packages\pip\
   from C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\~ip
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\base_command.py", line 228, in _main
    status = self.run(options, args)
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_internal\commands\install.py", line 397, in run
    installed = install_given_reqs(
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_internal\req\__init__.py", line 82, in install_given_reqs
    requirement.install(
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_internal\req\req_install.py", line 814, in install
    install_wheel(
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\install\wheel.py", line 852, in install_wheel
    _install_wheel(
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\install\wheel.py", line 762, in _install_wheel
    generated_console_scripts = maker.make_multiple(scripts_to_generate)
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 418, in make_multiple
    filenames.extend(self.make(specification, options))
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\install\wheel.py", line 498, in make
    return super(PipScriptMaker, self).make(specification, options)
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 407, in make
    self._make_script(entry, filenames, options=options)
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 307, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 242, in _write_script
    launcher = self._get_launcher('t')
  File "C:\Users\djiqu\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 386, in _get_launcher
    raise ValueError(msg)
ValueError: Unable to find resource t64.exe in package pip._vendor.distlib
WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
You should consider upgrading via the 'C:\Program Files\Compiler\Python\3.9\python.exe -m pip install --upgrade pip' command.
PS C:\Windows\system32>

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
